algoritmo "semnome"
// Função :
// Autor :
// Data : 09/01/2023
// Seção de Declarações 
var
   ano, nasc, idade : inteiro

inicio
      Escreva ("Em que ano estamos? ")
      leia(ano)
      Escreva ("Em que ano voce nasceu? ")
      leia (nasc)
      idade <- ano - nasc
      Escreva ("Em ", ano, " Voce tera ", idade , " Anos")
      Se (idade >= 21) entao
         Escreval (" e já tera atingido a Maioridade")
      FimSe
// Seção de Comandos 
fimalgoritmo
