Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2023
Var
// Seção de Declarações das variáveis 
nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
nome <- nome
escreva ("Digite seu nome:")
leia (nome)
escreva ("Muito prazer ", nome)


Fimalgoritmo